[package]
name = "zdisclosure-inspect"
description = "Prints the contents of a Sapling note Disclosure and what it opens"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
hex.workspace = true
zcash_disclosure.workspace = true
zdisclosure-cli.workspace = true
zdisclosure-core.workspace = true
